MyNUnit
kusancho/Programming_2Year pull request #10
Opened 2022-03-07 01:16 UTC by kusancho

2022-03-13 20:13 UTC, yurii-litvinov requested changes

2022-03-13 20:13 UTC, yurii-litvinov commented on src/MyNUnitImplementation/MyNUnitImplementation/MyNUnit.cs
> +            private object instance;
Не-а, на каждый тест instance должна создаваться своя. Потому что каждый тест надо запускать параллельно, и тогда общий instance --- это гарантированные гонки по данным между тестами.

2022-03-13 20:13 UTC, yurii-litvinov commented on src/MyNUnitImplementation/MyNUnitImplementation/MyNUnit.cs
> +                    if (!method.IsStatic)
Это стоит делать как-то централизованно (в ClassMethods, например), и с большим количеством проверок (например, методы не должны принимать аргументы и не должны ничего возвращать). А ещё я бы BeforeClass и AfterClass не запускал параллельно, из-за опасения гонок (справедливости ради, я бы вообще требовал, чтобы было ровно по одному такому методу в классе).

2022-03-13 20:13 UTC, yurii-litvinov commented on src/MyNUnitImplementation/MyNUnitImplementation/MyNUnit.cs
> +                        classLog.Add(new TestInfo(method.Name, TestStatus.Failed, reason: e.Message));
Это обычно не Failed, а Errored, и не на сам метод, а на все тесты из класса.

2022-03-13 20:13 UTC, yurii-litvinov commented on src/MyNUnitImplementation/MyNUnitImplementation/MyNUnit.cs
> +                    classLog.Add(new TestInfo(method.Name, TestStatus.Ignored, reason: e.Message));
Надо поправить предупреждения

2022-03-13 20:13 UTC, yurii-litvinov commented on src/MyNUnitImplementation/MyNUnitImplementation/MyNUnit.cs
> +                    classLog.Add(new TestInfo(method.Name, TestStatus.Passed, stopWatch.ElapsedMilliseconds));
Если исключение ожидалось, но не было брошено, тест запишется как пройденный, что неправда

2022-03-20 17:35 UTC, yurii-litvinov requested changes
Почти всё ок, но надо больше комментариев и стайлгайда.

2022-03-20 17:35 UTC, yurii-litvinov commented on src/MyNUnitImplementation/MyNUnitAttributes/After.cs
> +    }
```suggestion
```
Конструктор по умолчанию сгенерится и так

2022-03-20 17:35 UTC, yurii-litvinov commented on src/MyNUnitImplementation/MyNUnitImplementation/ClassMethods.cs
> +public class ClassMethods
И тут нужен коментарий :)

2022-03-20 17:35 UTC, yurii-litvinov commented on src/MyNUnitImplementation/MyNUnitImplementation/ClassMethods.cs
> +    public MethodInfo? AfterClass { get; private set; }
И ко всем паблик-свойствам тоже

2022-03-20 17:35 UTC, yurii-litvinov commented on src/MyNUnitImplementation/MyNUnitImplementation/ClassMethods.cs
> +            SanityCheckOfMarkedMethods(method);
Проверку-то лучше делать до .Add, чтобы если она не прошла, плохой метод не добавился. А то исключение в принципе можно и поймать и продолжить работу, тогда тут данные будут заполнены неправильно.

2022-03-20 17:35 UTC, yurii-litvinov commented on src/MyNUnitImplementation/MyNUnitImplementation/ClassTestingReport.cs
> +public class ClassTestingReport
С комментариями беда

2022-03-20 17:35 UTC, yurii-litvinov commented on src/MyNUnitImplementation/MyNUnitImplementation/MyNUnit.cs
> +                                    reason: $"Errored because of after class method falling: {e.Message}"));
"falling" по-английски в таких ситуациях не говорят, "упал" — это "crashed", ну или "failing" тут имелось в виду.

2022-03-20 17:35 UTC, yurii-litvinov commented on src/MyNUnitImplementation/MyNUnitImplementation/MyNUnit.cs
> +                            log.Reason = $"Errored because of after class method falling: {e.Message}";
Мы тут точно знаем, что after, а выше — что before, можно более специфичное сообщение об ошибке было писать.

2022-03-20 17:35 UTC, yurii-litvinov commented on src/MyNUnitImplementation/MyNUnitImplementation/MyNUnit.cs
> +                var property = (Test)Attribute.GetCustomAttribute(method, typeof(Test));
Компилятор выдаёт предупреждение, а не должен

2022-03-20 17:35 UTC, yurii-litvinov commented on src/MyNUnitImplementation/MyNUnitImplementation/MyNUnit.cs
> +            private bool RunAfterOrBeforeMethod(ConcurrentBag<MethodInfo> after, string name, object instance,
"after" как имя аргумента тут сбивает с толку

2022-03-20 17:35 UTC, yurii-litvinov commented on src/MyNUnitImplementation/MyNUnitImplementation/MyNUnit.cs
> +                bool IsBefore)
Параметры в .NET именуются со строчной всегда.

2022-03-20 17:35 UTC, yurii-litvinov commented on src/MyNUnitImplementation/MyNUnitImplementation/MyNUnit.cs
> +                            if (log.MethodName != name) return;
```suggestion
                            if (log.MethodName != name) 
                            {
                                return;
                            }
```
Это делает поток управления более явным

2022-03-20 17:35 UTC, yurii-litvinov commented on src/MyNUnitImplementation/MyNUnitImplementation/MyNUnit.cs
> +                    throw new ArgumentException("Method should be with `Test` attribute");
```suggestion
                    throw new ArgumentException("Method should have `Test` attribute");
```

2022-03-20 17:35 UTC, yurii-litvinov commented on src/MyNUnitImplementation/MyNUnitImplementation/TestInfo.cs
> +/// Test execution inforamtion
```suggestion
/// Test execution information
```
И ниже надо комментарии

2022-03-20 17:35 UTC, yurii-litvinov commented on src/MyNUnitImplementation/MyNUnitImplementation/TestStatus.cs
> +public enum TestStatus
И даже тут надо комментарии

2022-03-20 17:35 UTC, yurii-litvinov commented on src/MyNUnitImplementation/TestsForMyNUnit/UnitTest.cs
> +public class Tests
```suggestion
using System.Collections.Generic;

public class Tests
```

2022-03-20 17:35 UTC, yurii-litvinov commented on src/MyNUnitImplementation/TestsForMyNUnit/UnitTest.cs
> +    private MyNUnit testSession = new MyNUnit("../../../../TestData/bin/Debug/net6.0/");
```suggestion
    private MyNUnit testSession = new("../../../../TestData/bin/Debug/net6.0/");
```

2022-04-09 21:00 UTC, kusancho commented on src/MyNUnitImplementation/MyNUnitImplementation/MyNUnit.cs
> +                bool IsBefore)
очепятка

2022-04-12 15:15 UTC, yurii-litvinov approved these changes
Стало не идеально, но гораздо лучше, так что зачтена.

2022-04-12 15:15 UTC, yurii-litvinov commented on src/MyNUnitImplementation/MyNUnitImplementation/MyNUnit.cs
> +        /// <returns></returns>
:(

2022-04-12 15:15 UTC, yurii-litvinov commented on src/MyNUnitImplementation/MyNUnitImplementation/TestStatus.cs
> +    Passed,
И даже к каждому элементу enum-а по-хорошему.

2022-04-16 13:28 UTC, merged