Second homework
kusancho/Programming_2Year pull request #11
Opened 2022-03-11 20:43 UTC by kusancho

2022-03-19 20:56 UTC, DedSec256 requested changes
Есть некоторые замечания.

2022-03-19 20:56 UTC, DedSec256 commented on src/SecondHW/SecondHWTests/UnitTest.fs
> +    BinTree.map ((+) 1) beforeMap1 |> should equal <| BinTree(5, BinTree(4, BinTree(4, Null, Null), BinTree(4, Null, Null)), BinTree(5, Null, Null))
Не рекомендуется использовать |> ... <|, лучше уж в скобки обернуть.

2022-03-19 20:56 UTC, DedSec256 commented on src/SecondHW/SecondHWTests/UnitTest.fs
> +let ``amount of even in list`` () =
здесь задача тестирования состояла в том, чтобы ещё проверить на эквивалентность все функции с помощью генерации входных данных с помощью FsCheck, например

2022-03-19 20:56 UTC, DedSec256 commented on src/SecondHW/SecondHW/Program.fs
> +let infinitePrimes () =
очень большое злоупотребление бэкпайпом наблюдаю я! Бэкпайп скорее нерекомендован, чем рекомендован к использованию. Часто скобки понятнее.

2022-03-19 20:56 UTC, DedSec256 commented on src/SecondHW/SecondHW/Program.fs
> +    let isPrime n =
Попробуйте переписать эту функцию проще, без лишнего аккумулятора

2022-03-19 20:56 UTC, DedSec256 commented on src/SecondHW/SecondHW/Program.fs
> +        let border = int << sqrt << float <| n
здесь композиция проблему не решила, `int(sqrt(float n))` выглядит, возможно, даже лучше.
Вероятно, Вы хотели что-то вроде 
```suggestion
        let border = n |> float |> sqrt |> int
```

2022-03-24 22:54 UTC, DedSec256 commented on src/SecondHW/SecondHW/Program.fs
> +        let rec isDivisible divider acc =
Попробуйте переписать эту функцию без лишнего аккумулятора.

2022-04-16 13:57 UTC, kusancho commented on src/SecondHW/SecondHWTests/UnitTest.fs
> +    BinTree.map ((+) 1) beforeMap1 |> should equal <| BinTree(5, BinTree(4, BinTree(4, Null, Null), BinTree(4, Null, Null)), BinTree(5, Null, Null))
ok

2022-04-16 13:57 UTC, kusancho commented on src/SecondHW/SecondHWTests/UnitTest.fs
> +let ``amount of even in list`` () =
ok

2022-04-19 19:09 UTC, DedSec256 approved these changes

2022-04-19 20:34 UTC, merged