FirstHW
kusancho/Programming_2Year pull request #8
Opened 2022-02-28 21:09 UTC by kusancho

2022-03-02 21:32 UTC, DedSec256 requested changes
Похвально, что вы разобрались с CPS, но принцип KISS (keep it simple and straightforward) никто не отменял (:

2022-03-02 21:32 UTC, DedSec256 commented on src/FirstHW/FirstHW/FirstHW.fsproj
> +        <OutputType>Exe</OutputType>
если решили сделать домашку без `main`, то эту строку можно убрать, чтобы проект позиционировался как библиотека

2022-03-02 21:32 UTC, DedSec256 commented on src/FirstHW/FirstHW/Tasks.fs
> +    let rec cpsFactorial n k =
за академический финт с cps лайк (вы достигли второй половины мема), но передача континуации в виде лямбды в этой задаче сравнима со стрельбой из пушки по воробьям (:
лучше передавать обычный аккумулятор значением.


![image](https://user-images.githubusercontent.com/26364714/156451976-c1e917d2-cc83-438e-9604-998ac9777a95.png)

2022-03-02 21:32 UTC, DedSec256 commented on src/FirstHW/FirstHW/Tasks.fs
> +            helper (n - 2) (fun pp -> helper (n - 1) (fun p -> k (p + pp)))
как и в предыдущей задаче -- данную можно решить проще. Если можно решить проще -- лучше решить проще.

2022-03-02 21:32 UTC, DedSec256 commented on src/FirstHW/FirstHW/Tasks.fs
> +let rev lst =
задача засчитана

2022-03-02 21:32 UTC, DedSec256 commented on src/FirstHW/FirstHW/Tasks.fs
> +            makeListHelper (currentValue :: acc) (currentValue / 2) (currentLength + 1)
JFYI: не очень принятое форматирование, лучше `then` на той же строке оставлять, что и `if`

2022-03-02 21:32 UTC, DedSec256 commented on src/FirstHW/FirstHW/Tasks.fs
> +let find key lst =
задача засчитана

2022-03-02 21:37 UTC, DedSec256 commented on src/FirstHW/FirstHW/Tasks.fs
> +let makeListOfPowTwo n m =
эта задача тоже засчитана

2022-03-02 22:55 UTC, kusancho commented on src/FirstHW/FirstHW/Tasks.fs
> +    let rec cpsFactorial n k =
:feelsgood:

2022-03-03 11:25 UTC, DedSec256 approved these changes
👍

2022-03-05 14:04 UTC, merged